import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/assets/css/globals.css";
import { ThemeProvider } from "@/Provider/theme-provider";
import { ThemeButton } from "@/components/ui/themeButton";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Projeto",
    description: "Generated by create next app",
};



export default function LoginLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="pt-BR">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className=" md:w-2/3 lg:bg-blue-400 lg:dark:bg-blue-950">
                        <ThemeButton className=" border-2 border-zinc-300 dark:border-zinc-700" />
                    </div>
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}