import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers"
import { ThemeProvider } from "@/Provider/theme-provider";
import Navbar from "@/components/Navbar/Navbar";
import { ThemeButton } from "@/components/ui/themeButton";
import { headers } from "next/headers";
import { ToasterProvider } from "@/Provider/toaster-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Projeto",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  const cookieStore = await cookies();
  const headerStore = await headers();
  const pathname = headerStore.get("x-invoke-path") || headerStore.get("referer") || "";

  // Layout apenas para a página de login (sem navbar e sidebar)
  if (pathname.includes("/LoginPage")) {
    return (
      <html lang="pt-BR">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="p-4">
              <ToasterProvider />
              <ThemeButton className="border-2 border-zinc-300 dark:border-zinc-700" />
              {children}
            </main>
          </ThemeProvider>
        </body>
      </html>
    )
  }

  //Layout padrão para todos
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar>{children}</Navbar>
      </body>
    </html>
  );
}
